import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  videoBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  container: {
    paddingHorizontal: 24,
    paddingVertical: 48,
    justifyContent: 'center',
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  languageToggle: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 8,
  },
  languageToggleText: {
    color: '#000',
    fontWeight: '600',
    fontSize: 13,
  },
  logo: {
    height: 80,
    width: 260,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 12,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  description: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 20,
    fontSize: 14,
    lineHeight: 20,
  },
  section: {
    marginBottom: 24,
  },
  input: {
    borderColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    fontSize: 15,
    color: '#000',
    fontWeight: '500',
  },
  gradientButton: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    elevation: 3,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  linkContainer: {
    alignItems: 'center',
    marginTop: 12,
  },
  link: {
    color: '#5A9FFF',
    fontWeight: '600',
    fontSize: 14,
  },
  contact: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 12,
    fontSize: 13,
  },
  error: {
    color: '#e53935',
    marginBottom: 8,
    fontSize: 12,
    paddingLeft: 2,
  },
  generalErrorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff1f0',
    borderLeftWidth: 3,
    borderLeftColor: '#ff3b30',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    gap: 10,
  },
  generalError: {
    flex: 1,
    color: '#d32f2f',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  successContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f8f4',
    borderLeftWidth: 3,
    borderLeftColor: '#4caf50',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    gap: 10,
  },
  successText: {
    flex: 1,
    color: '#2e7d32',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  eyeIcon: {
    position: 'absolute',
    right: 16,
    top: 16,
  },
});
