import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  videoBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  container: {
    paddingHorizontal: 24,
    paddingVertical: 48,
    justifyContent: 'center',
    flexGrow: 1,
  },
  logo: {
    height: 80,
    width: 260,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 12,
  },
  description: {
    textAlign: 'center',
    color: '#555',
    marginBottom: 24,
    fontSize: 14,
    lineHeight: 20,
  },
  section: {
    marginBottom: 24,
  },
  input: {
    borderColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    fontSize: 15,
    color: '#000',
    fontWeight: '500',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  checkboxLabel: {
    flex: 1,
    color: '#fff',
    fontSize: 13,
    lineHeight: 18,
  },
  link: {
    color: '#5A9FFF',
    fontWeight: '600',
  },
  buttonWrapper: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  gradientButton: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    elevation: 3,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  linkRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  orContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  or: {
    marginHorizontal: 12,
    color: '#999',
    fontWeight: '600',
    fontSize: 13,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 24,
  },
  contact: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 12,
    fontSize: 13,
  },
  error: {
    color: '#e53935',
    marginBottom: 8,
    fontSize: 12,
    paddingLeft: 2,
  },
  generalErrorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff1f0',
    borderLeftWidth: 3,
    borderLeftColor: '#ff3b30',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    gap: 10,
  },
  generalError: {
    flex: 1,
    color: '#d32f2f',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  eyeIcon: {
    position: 'absolute',
    right: 16,
    top: 16,
  },
  languageToggle: {
    alignSelf: 'flex-end',
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 8,
  },
  languageToggleText: {
    color: '#000',
    fontWeight: '600',
    fontSize: 13,
  },
});
